### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error 

### ISSUE THREAD

**Issue by AdelCode** [baselhmidan/DMARC2Syslog#1]
Application could not connect to the exchange server due to https

ERROR    except       HTTPSConnectionPool(host='<exchange server url>', port=443): Max retries exceeded with url: <url>.asmx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by BHCyber** [comment]
Added a new option to bypass TLS/SSL certificate verification to connect to Exchange Web Service.
